spring:
  datasource:
    username: yalli_database_user
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    username: ${MAIL_EMAIL}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
          required: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
springdoc:
  swagger-ui:
    path: /api-docs
minio:
  url: https://minio-server-4oyt.onrender.com
  access-key: ${UPLOAD_PASSWORD}
  secret-key: ${UPLOAD_SECRET_KEY}
  name: yalli
